In [1]:
import numpy as np
from datascience import *

In [2]:
arr = make_array("Milo","Browder","California","Blue")

In [3]:
arr

array(['Milo', 'Browder', 'California', 'Blue'], dtype='<U10')

In [4]:
np.char.upper(arr)

array(['MILO', 'BROWDER', 'CALIFORNIA', 'BLUE'], dtype='<U10')

In [5]:
np.char.count(arr,"a")

array([0, 0, 2, 0])

In [6]:
sizes = [len(i) for i in arr]

In [7]:
sizes

[4, 7, 10, 4]

In [15]:
odd_arr=np.arange(1,45,4)

In [16]:
odd_arr

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41])

In [17]:
np.sum(odd_arr)

231

In [25]:
odd_arr1=odd_arr.astype(float)

In [26]:
np.prod(odd_arr1)

7579867420125.0

In [27]:
np.log(odd_arr)

array([0.        , 1.60943791, 2.19722458, 2.56494936, 2.83321334,
       3.04452244, 3.21887582, 3.36729583, 3.49650756, 3.61091791,
       3.71357207])

In [28]:
diff_array=np.diff(odd_arr)

In [29]:
np.sum(diff_array)

40