In [2]:
import numpy as np
from datascience import *

Make an arraay containg your first and last name, home state, and favorite color

In [3]:
arr = make_array("Milo","Browder","California","Blue")

In [4]:
arr

array(['Milo', 'Browder', 'California', 'Blue'], dtype='<U10')

Make all characters uppercase

In [6]:
np.char.upper(arr)

array(['MILO', 'BROWDER', 'CALIFORNIA', 'BLUE'], dtype='<U10')

Count the occurences of the letter "a"

In [7]:
np.char.count(arr,"a")

array([0, 0, 2, 0])

Count the character lengths of all parts of the array

In [8]:
sizes = [len(i) for i in arr]

In [9]:
sizes

[4, 7, 10, 4]

Create an array containing everyother odd number from 1 to 41

In [13]:
odd_arr=np.arange(1,45,4)

In [14]:
odd_arr

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41])

find the sum and product of the array

In [15]:
np.sum(odd_arr)

231

Convert the type to float

In [21]:
odd_arr1=odd_arr.astype(float)

In [22]:
np.prod(odd_arr1)

7579867420125.0

Find the log of the array

In [18]:
np.log(odd_arr)

array([0.        , 1.60943791, 2.19722458, 2.56494936, 2.83321334,
       3.04452244, 3.21887582, 3.36729583, 3.49650756, 3.61091791,
       3.71357207])

find the difference in between adjacent elements and then sum them

In [19]:
diff_array=np.diff(odd_arr)

In [20]:
np.sum(diff_array)

40